import type { Authority } from '@/lib/types';

export const AUTHORITIES: Authority[] = [
  {
    id: 'customs',
    icon: 'Building2',
    titleEn: 'Jordan Customs Department',
    titleAr: 'دائرة الجمارك الأردنية',
    roleEn: 'Primary border agency',
    roleAr: 'الجهة الحدودية الرئيسية',
    descriptionEn:
      'Classification, customs value, ASYCUDA declarations, duty and fee collection, selectivity, inspection, and release. All commercial imports and exports pass through Customs.',
    descriptionAr:
      'التصنيف والقيمة الجمركية وبيانات الأسيكودا وتحصيل الرسوم والأجور والانتقائية والمعاينة والإفراج. تمر جميع المستوردات والصادرات التجارية عبر الجمارك.',
    documentsEn: 'Invoice, packing list, B/L, authorization, permits from other agencies as attached',
    documentsAr: 'الفاتورة وقائمة التعبئة والبوليصة والتفويض وتصاريح الجهات الأخرى كمرفقات',
    portalUrl: 'https://www.customs.gov.jo',
    whenRequiredEn: 'Every commercial import and export',
    whenRequiredAr: 'كل استيراد وتصدير تجاري',
    typicalTimelineEn: 'Hours to several days depending on selectivity lane',
    typicalTimelineAr: 'ساعات إلى عدة أيام حسب مسار الانتقائية',
  },
  {
    id: 'jfda',
    icon: 'ShieldCheck',
    titleEn: 'JFDA — Food & Drug Administration',
    titleAr: 'المؤسسة العامة للغذاء والدواء',
    roleEn: 'Food, medicines, cosmetics, medical devices',
    roleAr: 'أغذية وأدوية ومستحضرات وأجهزة طبية',
    descriptionEn:
      'Registration, labelling compliance, and import control for food, pharmaceuticals, cosmetics, and medical devices. May require product registration and lab analysis before release.',
    descriptionAr:
      'التسجيل وامتثال البطاقات والرقابة على استيراد الأغذية والأدوية ومستحضرات التجميل والأجهزة الطبية. قد يتطلب تسجيل المنتج وتحليلاً مخبرياً قبل الإفراج.',
    documentsEn: 'Product label, registration/approval, certificate of analysis, ingredients list',
    documentsAr: 'بطاقة المنتج والتسجيل/الموافقة وشهادة التحليل وقائمة المكونات',
    portalUrl: 'https://www.jfda.jo',
    whenRequiredEn: 'Food, drinks, cosmetics, medicines, medical devices, related chemicals',
    whenRequiredAr: 'أغذية ومشروبات ومستحضرات وأدوية وأجهزة طبية وكيماويات ذات صلة',
    typicalTimelineEn: 'Days to weeks if registration or lab is needed',
    typicalTimelineAr: 'أيام إلى أسابيع إذا لزم التسجيل أو المختبر',
  },
  {
    id: 'jsmo',
    icon: 'CheckCircle2',
    titleEn: 'JSMO — Standards & Metrology',
    titleAr: 'مؤسسة المواصفات والمقاييس',
    roleEn: 'Conformity & Jordanian standards',
    roleAr: 'المطابقة والمواصفات الأردنية',
    descriptionEn:
      'Enforces standards and conformity assessment. Many consumer and industrial goods need a certificate of conformity or equivalent evidence before Customs release.',
    descriptionAr:
      'تفرض المواصفات وتقييم المطابقة. كثير من السلع الاستهلاكية والصناعية تحتاج شهادة مطابقة أو إثباتاً معادلاً قبل إفراج الجمارك.',
    documentsEn: 'Certificate of conformity, technical specification, test report',
    documentsAr: 'شهادة المطابقة والمواصفة الفنية وتقرير الفحص',
    portalUrl: 'https://www.jsmo.gov.jo',
    whenRequiredEn: 'Regulated consumer goods, appliances, construction materials, many industrial items',
    whenRequiredAr: 'سلع استهلاكية خاضعة وأجهزة ومواد بناء وكثير من الأصناف الصناعية',
    typicalTimelineEn: 'Depends on whether CoC is ready or testing is required',
    typicalTimelineAr: 'يعتمد على جاهزية شهادة المطابقة أو الحاجة للفحص',
  },
  {
    id: 'mit',
    icon: 'Briefcase',
    titleEn: 'Ministry of Industry, Trade & Supply',
    titleAr: 'وزارة الصناعة والتجارة والتموين',
    roleEn: 'Trade licences & restricted goods',
    roleAr: 'تراخيص التجارة والسلع المقيدة',
    descriptionEn:
      'Import/export policy, commercial registration linkage, and licences for restricted or controlled trade goods. Some categories need prior ministry approval.',
    descriptionAr:
      'سياسة الاستيراد والتصدير وربط السجل التجاري وتراخيص السلع التجارية المقيدة أو الخاضعة للرقابة. بعض الفئات تحتاج موافقة مسبقة من الوزارة.',
    documentsEn: 'Import licence (if required), commercial registration evidence, application forms',
    documentsAr: 'رخصة الاستيراد (إن لزم) وإثبات السجل التجاري ونماذج الطلب',
    portalUrl: 'https://www.mit.gov.jo',
    whenRequiredEn: 'Goods on restricted lists; certain strategic or monitored products',
    whenRequiredAr: 'السلع في قوائم القيود؛ منتجات استراتيجية أو مراقبة معينة',
    typicalTimelineEn: 'Variable — apply before shipment when licence is mandatory',
    typicalTimelineAr: 'متغير — قدّم قبل الشحن عندما تكون الرخصة إلزامية',
  },
  {
    id: 'agriculture',
    icon: 'Leaf',
    titleEn: 'Ministry of Agriculture',
    titleAr: 'وزارة الزراعة',
    roleEn: 'Plants, animals, agri-inputs, quarantine',
    roleAr: 'نباتات وحيوانات ومدخلات زراعية وحجر',
    descriptionEn:
      'Import permits and quarantine for live animals, plants, seeds, fertilizers, pesticides, and many food-origin products. Health and phytosanitary certificates from origin are often required.',
    descriptionAr:
      'تصاريح الاستيراد والحجر للحيوانات الحية والنباتات والبذور والأسمدة والمبيدات وكثير من المنتجات ذات الأصل الغذائي. الشهادات الصحية والنباتية من المنشأ غالباً مطلوبة.',
    documentsEn: 'Import permit, origin health/phytosanitary certificate, product details',
    documentsAr: 'تصريح الاستيراد وشهادة صحية/نباتية من المنشأ وبيانات المنتج',
    whenRequiredEn: 'Agricultural and many food-origin consignments',
    whenRequiredAr: 'الشحنات الزراعية وكثير من ذات الأصل الغذائي',
    typicalTimelineEn: 'Permit before loading; inspection common at arrival',
    typicalTimelineAr: 'التصريح قبل التحميل؛ المعاينة شائعة عند الوصول',
  },
  {
    id: 'telecom',
    icon: 'Radio',
    titleEn: 'Telecom Regulatory Commission',
    titleAr: 'هيئة تنظيم قطاع الاتصالات',
    roleEn: 'Type approval for radio & telecom',
    roleAr: 'اعتماد نوع للأجهزة اللاسلكية والاتصالات',
    descriptionEn:
      'Type approval for mobile phones, Wi-Fi, Bluetooth, radio, GPS, and other telecom equipment. Import without approval can lead to hold or refusal.',
    descriptionAr:
      'اعتماد نوع لهواتف الجوال والواي فاي والبلوتوث واللاسلكي وGPS وغيرها من أجهزة الاتصالات. الاستيراد دون اعتماد قد يؤدي إلى حجز أو رفض.',
    documentsEn: 'Type approval, frequency/technical datasheet',
    documentsAr: 'اعتماد النوع ونشرة التردد/الفنية',
    whenRequiredEn: 'Any radio-emitting or public-network terminal equipment',
    whenRequiredAr: 'أي أجهزة تصدر موجات أو طرفيات شبكات عامة',
    typicalTimelineEn: 'Obtain type approval before regular imports',
    typicalTimelineAr: 'احصل على اعتماد النوع قبل الاستيراد المنتظم',
  },
  {
    id: 'security',
    icon: 'Shield',
    titleEn: 'Security & controlled goods',
    titleAr: 'الأمن والسلع الخاضعة للرقابة',
    roleEn: 'Hazardous, dual-use, security-sensitive',
    roleAr: 'خطرة وازدواجية الاستخدام وحساسة أمنياً',
    descriptionEn:
      'Prior clearance for explosives, certain chemicals, dual-use items, and security-sensitive goods. Involves Civil Defense and/or security agencies depending on the product.',
    descriptionAr:
      'موافقة مسبقة للمتفجرات وبعض الكيماويات والمواد ازدواجية الاستخدام والسلع الحساسة أمنياً. يشمل الدفاع المدني و/أو الجهات الأمنية حسب المنتج.',
    documentsEn: 'Prior approval, SDS, end-use statement',
    documentsAr: 'موافقة مسبقة ونشرة السلامة وإقرار الاستخدام النهائي',
    whenRequiredEn: 'Hazardous, chemical, dual-use, and security-listed goods',
    whenRequiredAr: 'المواد الخطرة والكيماوية وازدواجية الاستخدام والمدرجة أمنياً',
    typicalTimelineEn: 'Must be secured before shipment arrives',
    typicalTimelineAr: 'يجب تأمينها قبل وصول الشحنة',
  },
  {
    id: 'aseza',
    icon: 'Globe',
    titleEn: 'ASEZA — Aqaba Special Economic Zone',
    titleAr: 'سلطة منطقة العقبة الاقتصادية الخاصة',
    roleEn: 'Special zone customs & investment regime',
    roleAr: 'نظام جمركي واستثماري للمنطقة الخاصة',
    descriptionEn:
      'Administers special procedures for entities and goods under the Aqaba SEZ regime. Coordinate with ASEZA when the consignee or destination falls under the zone.',
    descriptionAr:
      'تدير إجراءات خاصة للكيانات والبضائع تحت نظام منطقة العقبة. نسّق مع السلطة عندما يقع المرسل إليه أو الوجهة تحت المنطقة.',
    documentsEn: 'ASEZA-related registrations and zone-specific forms as applicable',
    documentsAr: 'تسجيلات المنطقة والنماذج الخاصة حسب الحالة',
    whenRequiredEn: 'ASEZA-registered importers / zone destinations',
    whenRequiredAr: 'المستوردون المسجلون في المنطقة / وجهات المنطقة',
    typicalTimelineEn: 'Align with Customs and ASEZA instructions for the case',
    typicalTimelineAr: 'وائم مع تعليمات الجمارك وسلطة المنطقة للحالة',
  },
  {
    id: 'tax',
    icon: 'Receipt',
    titleEn: 'Income & Sales Tax Department',
    titleAr: 'دائرة ضريبة الدخل والمبيعات',
    roleEn: 'GST and taxpayer registration',
    roleAr: 'ضريبة المبيعات وتسجيل المكلفين',
    descriptionEn:
      'General sales tax on imports is assessed with Customs. Importers must be properly registered; tax codes on the declaration must match the treatment of the goods.',
    descriptionAr:
      'تُقدَّر ضريبة المبيعات العامة على المستوردات مع الجمارك. يجب أن يكون المستورد مسجلاً بشكل صحيح؛ رموز الضريبة على البيان يجب أن تطابق معالجة البضاعة.',
    documentsEn: 'Tax registration number, any exemption decisions',
    documentsAr: 'الرقم الضريبي وأي قرارات إعفاء',
    whenRequiredEn: 'All taxable imports; exemption claims',
    whenRequiredAr: 'جميع المستوردات الخاضعة؛ مطالبات الإعفاء',
    typicalTimelineEn: 'Aligned with customs payment',
    typicalTimelineAr: 'متزامن مع الدفع الجمركي',
  },
  {
    id: 'act',
    icon: 'Container',
    titleEn: 'ACT — Aqaba Container Terminal',
    titleAr: 'محطة حاويات العقبة (ACT)',
    roleEn: 'Terminal operations & storage free time',
    roleAr: 'عمليات المحطة ومدة التخزين المجانية',
    descriptionEn:
      'Operates container handling at Aqaba. Publishes free storage days and demurrage tariffs. Last free day drives the operational deadline for clearance and gate-out.',
    descriptionAr:
      'تشغّل مناولة الحاويات في العقبة. تنشر أيام التخزين المجانية وتعرفة غرامات التأخير. آخر يوم مجاني يحدد الموعد التشغيلي للتخليص والخروج.',
    documentsEn: 'Delivery order, customs release, terminal payments',
    documentsAr: 'أمر التسليم والإفراج الجمركي ومدفوعات المحطة',
    portalUrl: 'https://www.act.com.jo',
    n4CapUrl: 'https://cap.act.com.jo/apex/cap.zul',
    whenRequiredEn: 'Every container discharged at ACT',
    whenRequiredAr: 'كل حاوية تُفرَّغ في ACT',
    typicalTimelineEn: 'Free days from discharge — confirm live tariff',
    typicalTimelineAr: 'أيام مجانية من التفريغ — أكد التعرفة الحية',
  },
];
