/**
 * Standard Jordan customs / brokerage terminology (EN ↔ AR).
 * Use these strings for consistency across UI and guides.
 */
export interface Term {
  id: string;
  en: string;
  ar: string;
  /** Short definition for glossary */
  defEn: string;
  defAr: string;
  category: 'declaration' | 'selectivity' | 'terminal' | 'docs' | 'accounting' | 'parties';
}

export const TERMS: Term[] = [
  {
    id: 'declaration',
    en: 'Customs declaration',
    ar: 'البيان الجمركي',
    defEn: 'The formal goods declaration lodged in ASYCUDA (SAD).',
    defAr: 'البيان الرسمي للبضاعة المقدَّم في نظام الأسيكودا (الوثيقة الإدارية الموحدة).',
    category: 'declaration',
  },
  {
    id: 'sad',
    en: 'SAD (Single Administrative Document)',
    ar: 'الوثيقة الإدارية الموحدة (SAD)',
    defEn: 'Standard form structure for the customs declaration.',
    defAr: 'الهيكل القياسي لنموذج البيان الجمركي.',
    category: 'declaration',
  },
  {
    id: 'hs',
    en: 'HS code',
    ar: 'رمز النظام المنسق (HS)',
    defEn: 'Harmonized System classification code for the goods.',
    defAr: 'رمز تصنيف النظام المنسق للبضاعة.',
    category: 'declaration',
  },
  {
    id: 'selectivity',
    en: 'Selectivity',
    ar: 'الانتقائية',
    defEn: 'Risk-based assignment of a processing lane after registration.',
    defAr: 'تعيين مسار المعالجة بناءً على المخاطر بعد تسجيل البيان.',
    category: 'selectivity',
  },
  {
    id: 'lane',
    en: 'Lane / channel',
    ar: 'المسرب',
    defEn: 'Processing path: green, yellow, red, or blue.',
    defAr: 'مسار المعالجة: أخضر أو أصفر أو أحمر أو أزرق.',
    category: 'selectivity',
  },
  {
    id: 'green',
    en: 'Green lane',
    ar: 'المسرب الأخضر',
    defEn: 'Facilitated path with limited intervention.',
    defAr: 'مسار ميسّر بتدخل محدود.',
    category: 'selectivity',
  },
  {
    id: 'yellow',
    en: 'Yellow lane',
    ar: 'المسرب الأصفر',
    defEn: 'Documentary examination before release progresses.',
    defAr: 'فحص وثائقي قبل تقدم الإفراج.',
    category: 'selectivity',
  },
  {
    id: 'red',
    en: 'Red lane',
    ar: 'المسرب الأحمر',
    defEn: 'Physical examination of the goods.',
    defAr: 'معاينة فعلية للبضاعة.',
    category: 'selectivity',
  },
  {
    id: 'blue',
    en: 'Blue lane',
    ar: 'المسرب الأزرق',
    defEn: 'Release with post-clearance audit possible.',
    defAr: 'إفراج مع إمكانية التدقيق اللاحق.',
    category: 'selectivity',
  },
  {
    id: 'inspection',
    en: 'Physical examination',
    ar: 'المعاينة الفعلية',
    defEn: 'Customs inspects goods against the declaration.',
    defAr: 'تفحص الجمارك البضاعة مقابل البيان.',
    category: 'selectivity',
  },
  {
    id: 'inspection_act',
    en: 'Inspection Act',
    ar: 'محضر المعاينة',
    defEn: 'Official record of examination findings in ASYCUDA.',
    defAr: 'السجل الرسمي لنتائج المعاينة في الأسيكودا.',
    category: 'selectivity',
  },
  {
    id: 'pca',
    en: 'Post-clearance audit (PCA)',
    ar: 'التدقيق اللاحق (الرقابة اللاحقة)',
    defEn: 'Verification of classification, value, or origin after release.',
    defAr: 'التحقق من التصنيف أو القيمة أو المنشأ بعد الإفراج.',
    category: 'selectivity',
  },
  {
    id: 'assessment',
    en: 'Assessment',
    ar: 'التقدير',
    defEn: 'Calculation of duties, taxes, and fees on the declaration.',
    defAr: 'احتساب الرسوم والضرائب والأجور على البيان.',
    category: 'declaration',
  },
  {
    id: 'release',
    en: 'Release order',
    ar: 'أمر الإفراج',
    defEn: 'Authority to remove goods after payment and controls.',
    defAr: 'الإذن بإخراج البضاعة بعد الدفع واستكمال الرقابة.',
    category: 'declaration',
  },
  {
    id: 'manifest',
    en: 'Cargo manifest',
    ar: 'بيان الحمولة (المنافيست)',
    defEn: 'Carrier’s list of cargo on the vessel or flight.',
    defAr: 'قائمة الناقل لبضاعة الباخرة أو الرحلة.',
    category: 'docs',
  },
  {
    id: 'bl',
    en: 'Bill of lading (B/L)',
    ar: 'بوليصة الشحن',
    defEn: 'Transport document issued by the carrier.',
    defAr: 'وثيقة النقل الصادرة عن الناقل.',
    category: 'docs',
  },
  {
    id: 'do',
    en: 'Delivery order (D/O)',
    ar: 'أمر التسليم',
    defEn: 'Shipping line document required for terminal release.',
    defAr: 'وثيقة الخط الملاحي اللازمة للإفراج من المحطة.',
    category: 'docs',
  },
  {
    id: 'coo',
    en: 'Certificate of origin',
    ar: 'شهادة المنشأ',
    defEn: 'Proof of country of origin for preference or controls.',
    defAr: 'إثبات بلد المنشأ للتفضيل أو الرقابة.',
    category: 'docs',
  },
  {
    id: 'invoice',
    en: 'Commercial invoice',
    ar: 'الفاتورة التجارية',
    defEn: 'Seller’s invoice used for value and description.',
    defAr: 'فاتورة البائع المستخدمة للقيمة والوصف.',
    category: 'docs',
  },
  {
    id: 'packing',
    en: 'Packing list',
    ar: 'قائمة التعبئة',
    defEn: 'Detail of packages, marks, and contents.',
    defAr: 'تفاصيل الطرود والعلامات والمحتويات.',
    category: 'docs',
  },
  {
    id: 'act',
    en: 'ACT (Aqaba Container Terminal)',
    ar: 'محطة حاويات العقبة (ACT)',
    defEn: 'Container terminal at Aqaba port.',
    defAr: 'محطة الحاويات في ميناء العقبة.',
    category: 'terminal',
  },
  {
    id: 'free_days',
    en: 'Free days / free time',
    ar: 'الأيام المجانية / المدة المجانية',
    defEn: 'Storage period before demurrage applies.',
    defAr: 'مدة التخزين قبل بدء غرامات التأخير.',
    category: 'terminal',
  },
  {
    id: 'demurrage',
    en: 'Demurrage',
    ar: 'غرامات التأخير (أرضيات)',
    defEn: 'Charges after free time expires.',
    defAr: 'الأجور بعد انتهاء المدة المجانية.',
    category: 'terminal',
  },
  {
    id: 'discharge',
    en: 'Discharge date',
    ar: 'تاريخ التفريغ',
    defEn: 'Date cargo is discharged at the terminal.',
    defAr: 'تاريخ تفريغ البضاعة في المحطة.',
    category: 'terminal',
  },
  {
    id: 'broker',
    en: 'Customs broker',
    ar: 'المخلص الجمركي',
    defEn: 'Licensed agent who lodges declarations.',
    defAr: 'الوكيل المرخّص الذي يقدّم البيانات الجمركية.',
    category: 'parties',
  },
  {
    id: 'importer',
    en: 'Importer',
    ar: 'المستورد',
    defEn: 'Party bringing goods into Jordan.',
    defAr: 'الطرف الذي يُدخل البضاعة إلى الأردن.',
    category: 'parties',
  },
  {
    id: 'tax_number',
    en: 'Tax number',
    ar: 'الرقم الضريبي',
    defEn: 'Taxpayer identification used in portal and invoices.',
    defAr: 'رقم المكلّف المستخدم في البوابة والفواتير.',
    category: 'parties',
  },
  {
    id: 'duties',
    en: 'Customs duties',
    ar: 'الرسوم الجمركية',
    defEn: 'Import duties assessed on the declaration.',
    defAr: 'رسوم الاستيراد المقدَّرة على البيان.',
    category: 'accounting',
  },
  {
    id: 'gst',
    en: 'Sales tax (GST)',
    ar: 'ضريبة المبيعات',
    defEn: 'General sales tax where applicable on taxable supplies.',
    defAr: 'ضريبة المبيعات العامة حيث تنطبق على التوريدات الخاضعة.',
    category: 'accounting',
  },
  {
    id: 'disbursement',
    en: 'Disbursement (pass-through)',
    ar: 'مدفوعات ممرَّرة (نيابة عن العميل)',
    defEn: 'Duties/fees paid on behalf of the client — not broker revenue.',
    defAr: 'رسوم وأجور تُدفع نيابة عن العميل — وليست إيراداً للمخلص.',
    category: 'accounting',
  },
  {
    id: 'pass_through',
    en: 'Pass-through amount',
    ar: 'المبلغ الممرَّر',
    defEn: 'Sum of duties + port/ACT + government charges — not revenue.',
    defAr: 'مجموع الرسوم + أجور الميناء/ACT + الرسوم الحكومية — ليس إيراداً.',
    category: 'accounting',
  },
  {
    id: 'port_fees',
    en: 'Port / ACT fees',
    ar: 'أجور الميناء / محطة الحاويات',
    defEn: 'Terminal and port handling charges (usually pass-through).',
    defAr: 'أجور المحطة والمناولة في الميناء (عادةً ممرَّرة).',
    category: 'accounting',
  },
  {
    id: 'gov_charges',
    en: 'Other government charges',
    ar: 'رسوم حكومية أخرى',
    defEn: 'Permits, stamps, or authority fees paid for the client.',
    defAr: 'تصاريح أو طوابع أو رسوم جهات تُدفع لصالح العميل.',
    category: 'accounting',
  },
  {
    id: 'agency_fee',
    en: 'Agency / clearance fee',
    ar: 'أتعاب التخليص',
    defEn: 'Broker service charge — the only amount that is company revenue.',
    defAr: 'أجر خدمة المخلص — المبلغ الوحيد الذي يُعد إيراداً للشركة.',
    category: 'accounting',
  },
  {
    id: 'clearing_122100',
    en: 'Clearing receivable 122100',
    ar: 'ذمم التسوية 122100',
    defEn: 'Asset account when the broker pays first, then recovers from the client.',
    defAr: 'حساب أصل عندما يدفع المخلص أولاً ثم يسترد من العميل.',
    category: 'accounting',
  },
  {
    id: 'clearing_222100',
    en: 'Clearing prepay 222100',
    ar: 'دفعات مقدمة للتسوية 222100',
    defEn: 'Liability account for client advances against expected charges.',
    defAr: 'حساب التزام لمقدمات العميل مقابل الرسوم المتوقعة.',
    category: 'accounting',
  },
  {
    id: 'revenue_411100',
    en: 'Agency revenue 411100',
    ar: 'إيراد خدمة التخليص 411100',
    defEn: 'Income account for clearance fees only — never for duties.',
    defAr: 'حساب إيراد لأتعاب التخليص فقط — وليس للرسوم الجمركية.',
    category: 'accounting',
  },
  {
    id: 'cash_bank',
    en: 'Cash / bank 111000',
    ar: 'الصندوق / البنك 111000',
    defEn: 'Bank movements for duty payment, recovery, and fee collection.',
    defAr: 'حركات البنك لدفع الرسوم والاسترداد وتحصيل الأتعاب.',
    category: 'accounting',
  },
  {
    id: 'cost_511100',
    en: 'Cost of clearance service 511100',
    ar: 'تكلفة خدمة التخليص 511100',
    defEn: 'Optional direct cost of the service — not customs duties.',
    defAr: 'تكلفة مباشرة اختيارية للخدمة — وليست الرسوم الجمركية.',
    category: 'accounting',
  },
  {
    id: 'debit',
    en: 'Debit',
    ar: 'مدين',
    defEn: 'Debit side of a journal entry; increases assets and expenses.',
    defAr: 'الجانب المدين من القيد؛ يزيد الأصول والمصروفات.',
    category: 'accounting',
  },
  {
    id: 'credit',
    en: 'Credit',
    ar: 'دائن',
    defEn: 'Credit side of a journal entry; increases liabilities and revenue.',
    defAr: 'الجانب الدائن من القيد؛ يزيد الالتزامات والإيرادات.',
    category: 'accounting',
  },
  {
    id: 'journal_entry',
    en: 'Journal entry',
    ar: 'قيد يومية',
    defEn: 'Balanced debit and credit posting for one transaction.',
    defAr: 'تسجيل متوازن مدين ودائن لعملية مالية واحدة.',
    category: 'accounting',
  },
  {
    id: 'chart_of_accounts',
    en: 'Chart of accounts',
    ar: 'دليل الحسابات',
    defEn: 'Structured list of account codes used in the books.',
    defAr: 'قائمة منظّمة برموز الحسابات المستخدمة في الدفاتر.',
    category: 'accounting',
  },
  {
    id: 'pay_first',
    en: 'Pay-first mode',
    ar: 'نمط الدفع أولاً',
    defEn: 'Broker pays duties then recovers from client through 122100.',
    defAr: 'المخلص يدفع الرسوم ثم يسترد من العميل عبر 122100.',
    category: 'accounting',
  },
  {
    id: 'client_prepay',
    en: 'Client prepayment mode',
    ar: 'نمط الدفع المقدم من العميل',
    defEn: 'Client advances funds; broker applies them through 222100.',
    defAr: 'العميل يدفع مقدماً؛ يطبّق المخلص المبلغ عبر 222100.',
    category: 'accounting',
  },
  {
    id: 'true_up',
    en: 'True-up / settlement difference',
    ar: 'التسوية (فرق المقدم عن الفعلي)',
    defEn: 'Difference between prepay and actual charges (shortfall or refund).',
    defAr: 'الفرق بين المقدمة والرسوم الفعلية (عجز أو رد).',
    category: 'accounting',
  },
  {
    id: 'recovery',
    en: 'Client recovery / reimbursement',
    ar: 'الاسترداد / التحصيل من العميل',
    defEn: 'Client pays back pass-through amounts the broker advanced.',
    defAr: 'العميل يسدد المبالغ الممرَّرة التي دفعها المخلص.',
    category: 'accounting',
  },
  {
    id: 'shortfall',
    en: 'Shortfall',
    ar: 'عجز (الفعلي أعلى من المقدم)',
    defEn: 'Actual charges exceed prepay; extra amount due from client.',
    defAr: 'الرسوم الفعلية أعلى من المقدمة؛ الزيادة مستحقة على العميل.',
    category: 'accounting',
  },
  {
    id: 'excess_prepay',
    en: 'Excess prepayment / refund',
    ar: 'فائض المقدمة / الرد للعميل',
    defEn: 'Prepay exceeds actual charges; surplus is returned to the client.',
    defAr: 'المقدمة أعلى من الرسوم الفعلية؛ يُرد الفائض للعميل.',
    category: 'accounting',
  },
  {
    id: 'receivable',
    en: 'Receivable (asset)',
    ar: 'ذمم مدينة (أصل)',
    defEn: 'Amount owed to the broker (e.g. open balance on 122100).',
    defAr: 'مبلغ مستحق للمخلص (مثل رصيد مفتوح على 122100).',
    category: 'accounting',
  },
  {
    id: 'liability_term',
    en: 'Liability',
    ar: 'التزام',
    defEn: 'Amount the broker owes (e.g. unapplied client prepay on 222100).',
    defAr: 'مبلغ على المخلص (مثل مقدمة عميل غير مطبَّقة على 222100).',
    category: 'accounting',
  },
  {
    id: 'balance_sheet',
    en: 'Balance sheet',
    ar: 'الميزانية العمومية',
    defEn: 'Assets and liabilities; clearing balances stay here until cleared.',
    defAr: 'الأصول والالتزامات؛ أرصدة التسوية تبقى هنا حتى التصفية.',
    category: 'accounting',
  },
  {
    id: 'pnl',
    en: 'Profit & loss (P&L)',
    ar: 'قائمة الدخل',
    defEn: 'Should show agency fee revenue only — not pass-through duties.',
    defAr: 'يجب أن تظهر إيراد الأتعاب فقط — وليس الرسوم الممرَّرة.',
    category: 'accounting',
  },
  {
    id: 'turnover_inflation',
    en: 'Turnover inflation (wrong booking)',
    ar: 'تضخيم حجم الأعمال (تقييد خاطئ)',
    defEn: 'Booking duties as sales and cost overstates revenue and activity.',
    defAr: 'تقييد الرسوم كمبيعات وتكلفة يضخّم الإيراد وحجم النشاط بشكل خاطئ.',
    category: 'accounting',
  },
  {
    id: 'client_statement',
    en: 'Client recovery statement',
    ar: 'كشف استرداد العميل',
    defEn: 'Breakdown of pass-through charges plus agency fee due from client.',
    defAr: 'تفصيل الرسوم الممرَّرة وأتعاب التخليص المستحقة على العميل.',
    category: 'accounting',
  },
  {
    id: 'settlement',
    en: 'File settlement / close',
    ar: 'تسوية الملف / الإقفال',
    defEn: 'Clearing account back to zero and fee recognized for the declaration.',
    defAr: 'إعادة حساب التسوية إلى صفر والاعتراف بالأتعاب لهذا البيان.',
    category: 'accounting',
  },
  {
    id: 'asycuda',
    en: 'ASYCUDA World',
    ar: 'الأسيكودا العالمي',
    defEn: 'UNCTAD customs system used by Jordan Customs.',
    defAr: 'نظام الجمارك التابع للأونكتاد والمستخدَم لدى دائرة الجمارك الأردنية.',
    category: 'declaration',
  },

];

export const TERM_CATEGORIES: {
  id: Term['category'];
  en: string;
  ar: string;
}[] = [
  { id: 'declaration', en: 'Declaration & tariff', ar: 'البيان والتعرفة' },
  { id: 'selectivity', en: 'Selectivity & control', ar: 'الانتقائية والرقابة' },
  { id: 'docs', en: 'Documents', ar: 'الوثائق' },
  { id: 'terminal', en: 'Terminal & free time', ar: 'المحطة والمدة المجانية' },
  { id: 'parties', en: 'Parties', ar: 'الأطراف' },
  { id: 'accounting', en: 'Accounting & clearing', ar: 'المحاسبة وحسابات التسوية' },
];
